ip: 192.168.0.107
server:
  port: 8771
  address: ${ip}
#192.168.43.237
eureka:
  instance:
    hostname: ${ip}
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: product-server
  zipkin:
    base-url: http://${ip}:9411
  sleuth:
    sampler:
      probability: 1
